altrp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog.views import (
    BlogDetail, BlogList, BlogCreateView,
    BlogDeleteView, BLogUpdateView, CategoryCreateView,
    CategoryList, CategoryDetail, CategoryUpdateView, CategoryDeleteView

)

urlpatterns = [
    path('', BlogList.as_view(), name='home'),
    path('category', CategoryList.as_view(), name='category_list_url'),
    path('blog/<slug:slug>/', BlogDetail.as_view(), name='blog_detail'),
    path('category/<slug:slug>/', CategoryDetail.as_view(), name='category_detail'),
    path('blog/add/', BlogCreateView.as_view(), name='blog_create_url'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create_url'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete_url'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete_url'),
    path('blog/<int:pk>/edit/', BLogUpdateView.as_view(), name='blog_update_url'),
    path('category/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category_update_url'),
]

blog/models.py
from django.db import models
from django.urls import reverse


class Blog(models.Model):
    """ Модель блока """
    name = models.CharField(max_length=255, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(verbose_name='Изображение', upload_to='media/blog/', blank=True, null=True)
    short_description = models.CharField(max_length=255, verbose_name='Краткого описания')
    description = models.TextField(verbose_name='Полного описания')
    created = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        ordering = ['-created']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('blog_update_url', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('blog_delete_url', kwargs={'pk': self.pk})


class Category(models.Model):
    """ Модель категории """
    name = models.CharField(max_length=255, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True)
    blog = models.ForeignKey('Blog', verbose_name='Блог', related_name='categories', on_delete=models.CASCADE)
    photo = models.ImageField(verbose_name='Изображение', upload_to='media/category/', blank=True, null=True)
    created = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['-created']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('category_update_url', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('category_delete_url', kwargs={'pk': self.pk})

blog/views.py
from django.urls import reverse_lazy
from django.views import generic

from blog.models import Blog, Category


class BlogList(generic.ListView):
    """ Список блоков """

    queryset = Blog.objects.all().order_by('-created')
    template_name = 'index.html'


class CategoryList(generic.ListView):
    """ Список Категории """
    queryset = Category.objects.all().order_by('-created')
    template_name = 'category_list.html'


class BlogDetail(generic.DetailView):
    """ Подробности блога """
    model = Blog
    context_object_name = 'blog'
    template_name = 'blog_detail.html'


class CategoryDetail(generic.DetailView):
    """ Подробности Категории """
    model = Category
    context_object_name = 'category'
    template_name = 'category_detail.html'


class BlogCreateView(generic.CreateView):
    model = Blog
    template_name = 'blog_create.html'
    fields = '__all__'


class BLogUpdateView(generic.UpdateView):
    model = Blog
    context_object_name = 'blog'
    template_name = 'blog_update.html'
    fields = "__all__"


class CategoryUpdateView(generic.UpdateView):
    model = Category
    context_object_name = 'category'
    template_name = 'category_update.html'
    fields = "__all__"


class BlogDeleteView(generic.DeleteView):
    model = Blog
    context_object_name = 'blog'
    template_name = 'blog_delete.html'
    success_url = reverse_lazy('home')


class CategoryDeleteView(generic.DeleteView):
    model = Category
    context_object_name = 'category'
    template_name = 'category_delete.html'
    success_url = reverse_lazy('category_list')


class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = 'category_create.html'
    fields = '__all__'

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous"/>
</head>
</head>

<body>
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 17px;
        background-color: #fdfdfd;
    }

    .shadow {
        box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
    }

    .btn-danger {
        color: #fff;
        background-color: #f00000;
        border-color: #dc281e;
    }

    .masthead {
        background: #3398E1;
        height: auto;
        padding-bottom: 15px;
        box-shadow: 0 16px 48px #E3E7EB;
        padding-top: 10px;
    }
</style>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Talp group</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'blog_create_url'%}">Blog Create</a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'category_create_url'%}">Category
                        Create</a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'category_list_url'%}">Category
                        List</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}
<!-- Content Goes here -->
{% endblock content %}
<!-- Footer -->
<footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">Talp group blogs</p>
</footer>
</body>
</html>

templates/blog_create.html
{% extends 'base.html' %}

{% block title %}
{{ block.super }} Create
{% endblock %}

{% block content %}

<form action="{% url 'blog_create_url' %}" method="post">

    {% csrf_token %}

    {% for field in form %}
    <div class="form-group">
        {% if field.errors %}
        <div class="alert alert-danger">
            {{ field.errors }}
        </div>
        {% endif %}

        {{ field.label }}
        {{ field }}
    </div>
    {% endfor %}


    <button type="submit" class="btn btn-primary">Blog Create</button>

</form>
{% endblock %}

templates/blog_delete.html
{% extends 'base.html' %}

{% block title %}
{{ block.super }} Delete
{% endblock %}

{% block content %}

<form action="{{ blog.get_delete_url }}" method="POST">
    {% csrf_token %}
    <h3>Are you sure you want to delete <b>"{{ blog.name|title }}"</b></h3>
    <a href="{{blog.get_absolute_url}}">Cancel</a>
    <button type="submit" name='button' class="btn btn-danger">Submit</button>

</form>

{% endblock %}

templates/blog_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="card">
        <h5 class="card-header"><span class="text-primary">{{ blog.name }}</span></h5>
        <div class="card-body">
            <h5 class="card-title">Published: {{ blog.created }}</h5>
            <li style="list-style: none"><span><b>Категории блока:</b>
                        {% for category in blog.categories.all %}
                            <a href="#">
                                    {{ category.name }}
                            </a>
                        {% endfor %}
                                </span>
            </li>
            <br>
            <img src="{{blog.photo.url}}" width="100" height="100">
            <p class="card-text">{{ blog.short_description }}</p>
            <br>
            <p class="card-text">{{ blog.description }}</p>
        </div>
    </div>
</div>
{% endblock content %}

templates/blog_update.html
{% extends 'base.html' %}

{% block title %}
{{ block.super }} Update
{% endblock %}

{% block content %}
<form action="{{ blog.get_update_url }}" method="post">

    {% csrf_token %}

    {% for field in form %}
    <div class="form-group">
        {% if field.errors %}
        <div class="alert alert-danger">
            {{ field.errors }}
        </div>
        {% endif %}

        {{ field.label }}
        {{ field }}
    </div>
    {% endfor %}


    <button type="submit" class="btn btn-primary">Update Blog</button>

</form>
{% endblock %}

templates/category_create.html
{% extends 'base.html' %}

{% block title %}
{{ block.super }} Create
{% endblock %}

{% block content %}

<form action="{% url 'category_create_url' %}" method="post">

    {% csrf_token %}

    {% for field in form %}
    <div class="form-group">
        {% if field.errors %}
        <div class="alert alert-danger">
            {{ field.errors }}
        </div>
        {% endif %}

        {{ field.label }}
        {{ field }}
    </div>
    {% endfor %}


    <button type="submit" class="btn btn-primary">Category Create</button>

</form>
{% endblock %}

templates/category_delete.html
{% extends 'base.html' %}

{% block title %}
{{ block.super }} Delete
{% endblock %}

{% block content %}

<form action="{{ category.get_delete_url }}" method="POST">
    {% csrf_token %}
    <h3>Are you sure you want to delete <b>"{{ category.name|title }}"</b></h3>
    <a href="{{category.get_absolute_url}}">Cancel</a>
    <button type="submit" name='button' class="btn btn-danger">Submit</button>

</form>

{% endblock %}

templates/category_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="card">
        <h5 class="card-header"><span class="text-primary">{{ category.name }}</span></h5>
        <div class="card-body">
            <h5 class="card-title">Published: {{ category.created }}</h5>

            <p class="card-text">Blog: {{ category.blog }}</p>
            <img src="{{category.image.url}}" width="100" height="100">
        </div>
    </div>
</div>
{% endblock content %}

templates/category_list.html
{% extends "base.html" %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">

            {% for category in category_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ category.name }}</h2>
                    <p class="card-text text-muted h6">{{ category.created}} </p>
                    <p class="card-text">{{category.content|slice:":200" }}</p>
                    <img src="{{category.image.url}}" width="100" height="100">
                    <a href="{{ category.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
                    <a href="{{ category.get_update_url }}" class="btn btn-primary">edit &rarr;</a>
                    <a href="{{ category.get_delete_url }}" class="btn btn-primary">delete &rarr;</a></td>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock%}

templates/category_update.html
{% extends 'base.html' %}

{% block title %}
{{ block.super }} Update
{% endblock %}

{% block content %}
<form action="{{ category.get_update_url }}" method="post">

    {% csrf_token %}

    {% for field in form %}
    <div class="form-group">
        {% if field.errors %}
        <div class="alert alert-danger">
            {{ field.errors }}
        </div>
        {% endif %}

        {{ field.label }}
        {{ field }}
    </div>
    {% endfor %}


    <button type="submit" class="btn btn-primary">Update Blog</button>

</form>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            <h3>
                <a href="{% url 'category_list_url'%}">List Category</a>
            </h3>
            {% for blog in blog_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ blog.name }}</h2>
                    <p class="card-text text-muted h6">{{ blog.short_description }} | {{ blog.created}} </p>
                    <p class="card-text">{{blog.content|slice:":200" }}</p>
                    <img src="blog.image.url" width="100" height="100">
                    <li style="list-style: none"><span><b>Категории блока:</b>
                        {% for category in blog.categories.all %}
                            <a href="{{ category.get_absolute_url }}">
                                    {{ category.name }}
                            </a>
                        {% endfor %}
                                </span>
                    </li>

                    <a href="{{ blog.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
                    <a href="{{ blog.get_update_url }}" class="btn btn-primary">edit &rarr;</a>
                    <a href="{{ blog.get_delete_url }}" class="btn btn-primary">delete &rarr;</a></td>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock%}

templates/sidebar.html
{% block sidebar %}

<style>
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
    <div class="card my-4">
        <h5 class="card-header">About Us</h5>
        <div class="card-body">
            <p class="card-text"> Our working chat, where you can ask questions on the technical side, send the
                completed task also to our chat</p>
            <a href="https://docs.google.com/document/d/1C0uAHLdB1KRt_cwV8_qkBbqJyStaPeLs3xvHotBWU7w/edit"
               class="btn btn-danger">Know more!</a>
        </div>
    </div>
</div>

{% endblock sidebar %}